<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Обработка ошибок с try...catch</title>
    <link rel="stylesheet" href="css/common6.css" />
  </head>
  <body>
    <p><a href="index.html">На главную</a></p>

    <script src="js/17-try-catch.js"></script>
  </body>
</html>

<!-- - Обработка ошибок с try...catch
  - Синтаксис
  - Какие ошибки ловит
    - ❌ время оценки (чтения) - ошибки парсинга (parsing errors)
    - ✅ время выполнения скрипта - ошибки выполнения (runtime errors)
    - [http://fecore.net.ua/books/m5ph3r-javascript/module-02/scope.html#hoisting](http://fecore.net.ua/books/m5ph3r-javascript/module-02/scope.html#hoisting)
  - Ловит только ошибки в синхронном коде
    - Как словить ошибку в асинхронном коде
  - Объект ошибки
    - name
    - message
    - stack
  - Блок catch без ошибки
  - Использование - грамотный парс JSON
- Parceljs и async/await. Ошибка regenerator runtime
- Синтаксис async/await -->
